import { ipcRenderer, contextBridge } from 'electron';

console.log('[HermsDesk] Preload script initializing...');
contextBridge.exposeInMainWorld('ipcRenderer', {
  on(channel: string, listener: (event: Electron.IpcRendererEvent, ...args: any[]) => void) {
    return ipcRenderer.on(channel, (event: Electron.IpcRendererEvent, ...args: any[]) => listener(event, ...args));
  },
  off(channel: string, ...args: any[]) {
    // @ts-ignore
    return ipcRenderer.off(channel, ...args);
  },
  send(channel: string, ...args: any[]) {
    // @ts-ignore
    return ipcRenderer.send(channel, ...args);
  },
  invoke(channel: string, ...args: any[]) {
    // @ts-ignore
    return ipcRenderer.invoke(channel, ...args);
  },
  removeAllListeners(channel: string) {
    return ipcRenderer.removeAllListeners(channel);
  },

  // AI & Local Engine — Built-in Jan + TurboQuant (PRIMARY)
  listModels: () => ipcRenderer.invoke('ai:list-models'),
  chat: (data: any) => ipcRenderer.invoke('ai:chat', data),
  checkLMStudio: () => ipcRenderer.invoke('ai:check-lmstudio'),
  checkOpenCode: () => ipcRenderer.invoke('ai:check-opencode'),
  listOpenCodeModels: () => ipcRenderer.invoke('ai:list-opencode-models'),
  checkJan: () => ipcRenderer.invoke('ai:check-jan'),
  janStatus: () => ipcRenderer.invoke('ai:jan-status'),
  modelHubDiagnostics: () => ipcRenderer.invoke('ai:model-hub-diagnostics'),
  startJan: () => ipcRenderer.invoke('ai:start-jan'),
  loadJanModel: (model: any) => ipcRenderer.invoke('ai:load-jan-model', model),
  scanPC: () => ipcRenderer.invoke('ai:scan-pc'),
  getResourceUsage: () => ipcRenderer.invoke('ai:get-resource-usage'),

  // ME 1.8 — Full engine status and smart routing
  engineStatus: () => ipcRenderer.invoke('ai:engine-status'),
  chatBest: (data: any) => ipcRenderer.invoke('ai:chat-best', data),
  
  // New Providers & HF
  searchHF: (query: string) => ipcRenderer.invoke('ai:search-hf', query),
  downloadHF: (modelId: string) => ipcRenderer.invoke('ai:download-hf', modelId),
  getModelsPath: () => ipcRenderer.invoke('ai:get-models-path'),
  listLibraryModels: () => ipcRenderer.invoke('ai:list-library-models'),
  deleteLibraryModel: (modelId: string) => ipcRenderer.invoke('ai:delete-library-model', modelId),
  revealModelsFolder: () => ipcRenderer.invoke('ai:reveal-models-folder'),
  chatProvider: (data: any) => ipcRenderer.invoke('ai:chat-provider', data),

  // Connectors & Social
  connectGoogle: () => ipcRenderer.invoke('ai:connect-google'),
  saveAPIKey: (provider: string, key: string) => ipcRenderer.invoke('ai:save-api-key', { provider, key }),
  getAPIKeys: () => ipcRenderer.invoke('ai:get-api-keys'),
  getKnowledge: () => ipcRenderer.invoke('knowledge:get-all'),
  saveKnowledge: (knowledge: any) => ipcRenderer.invoke('knowledge:save', knowledge),

  // Desktop Integrations
  openApp: (appName: string) => ipcRenderer.invoke('app:open', appName),
  selectFiles: () => ipcRenderer.invoke('file:select-files'),
  selectFolder: () => ipcRenderer.invoke('file:select-folder'),
  analyzeUK: (path: string, type: string) => ipcRenderer.invoke('file:analyze-uk', { path, type }),

  // Tool Registry
  getTools: () => ipcRenderer.invoke('tools:get-all'),
  getConnectors: () => ipcRenderer.invoke('tools:get-connectors'),
  saveConnector: (connector: any) => ipcRenderer.invoke('tools:save-connector', connector),
  toggleConnector: (id: string, enabled: boolean) => ipcRenderer.invoke('tools:toggle-connector', { id, enabled }),
  executeTool: (toolId: string, params: any) => ipcRenderer.invoke('tools:execute', { toolId, params }),

  // Skills Engine
  getInstalledSkills: () => ipcRenderer.invoke('skills:get-installed'),
  getSkillGuidance: () => ipcRenderer.invoke('skills:get-guidance'),
  getSkillPackages: () => ipcRenderer.invoke('skills:get-packages'),
  toggleSkill: (skillId: string, installed: boolean) => ipcRenderer.invoke('skills:toggle', { skillId, installed }),
  proposeSkill: (action: any) => ipcRenderer.invoke('skills:propose', action),
  getPendingSkills: () => ipcRenderer.invoke('skills:get-pending'),
  approveSkill: (id: string) => ipcRenderer.invoke('skills:approve', id),
  denySkill: (id: string) => ipcRenderer.invoke('skills:deny', id),
  getSelfImprovementState: () => ipcRenderer.invoke('self-improvement:get-state'),
  runSelfImprovementCheck: (reason?: string) => ipcRenderer.invoke('self-improvement:run-now', reason),

  // Multi-Agent Orchestrator
  getAgents: () => ipcRenderer.invoke('agents:get-all'),
  updateAgentStatus: (id: string, status: string, background: boolean) => ipcRenderer.invoke('agents:update-status', { id, status, background }),
  createAgentTask: (input: any, agentId: any) => ipcRenderer.invoke('agents:create-task', { input, agentId }),
  previewAgentRoute: (input: any, agentId?: any) => ipcRenderer.invoke('agents:preview-route', { input, agentId }),
  getAgentTasks: () => ipcRenderer.invoke('agents:get-tasks'),
  stopOperatorMode: (reason?: string) => ipcRenderer.invoke('operator:stop-all', reason),
  injectOperatorInstruction: (agentId: string, instruction: string) => ipcRenderer.invoke('operator:inject', { agentId, instruction }),

  // Workspace
  getMailSettings: () => ipcRenderer.invoke('workspace:get-mail'),
  saveMailSettings: (settings: any) => ipcRenderer.invoke('workspace:save-mail', settings),
  getWhatsAppDrafts: () => ipcRenderer.invoke('workspace:get-whatsapp-drafts'),
  saveWhatsAppDraft: (draft: any) => ipcRenderer.invoke('workspace:save-whatsapp-draft', draft),
  markWhatsAppOpened: (id: string) => ipcRenderer.invoke('workspace:mark-whatsapp-opened', id),
  getWhatsAppChannelStatus: () => ipcRenderer.invoke('whatsapp:status'),
  ensureWhatsAppActive: () => ipcRenderer.invoke('whatsapp:ensure-active'),
  getWhatsAppChannelSettings: () => ipcRenderer.invoke('whatsapp:settings'),
  saveWhatsAppChannelSettings: (settings: any) => ipcRenderer.invoke('whatsapp:save-settings', settings),
  getWhatsAppRoutes: () => ipcRenderer.invoke('whatsapp:routes'),
  routeWhatsAppMessage: (text: string, from: any) => ipcRenderer.invoke('whatsapp:route-message', { text, from }),
  composeWhatsAppDraft: (draftId: string) => ipcRenderer.invoke('whatsapp:compose-draft', draftId),
  startWhatsAppLocalBridge: (ownerPhone?: string) => ipcRenderer.invoke('whatsapp:start-local-bridge', { ownerPhone }),
  stopWhatsAppLocalBridge: () => ipcRenderer.invoke('whatsapp:stop-local-bridge'),
  getScheduledTasks: () => ipcRenderer.invoke('workspace:get-tasks'),
  saveScheduledTasks: (tasks: any) => ipcRenderer.invoke('workspace:save-tasks', tasks),
  runScheduledTask: (id: string) => ipcRenderer.invoke('workspace:run-scheduled-task', id),
  getScheduledRuns: () => ipcRenderer.invoke('workspace:get-scheduled-runs'),
  getGeneralSettings: () => ipcRenderer.invoke('workspace:get-settings'),
  saveGeneralSettings: (settings: any) => ipcRenderer.invoke('workspace:save-settings', settings),
  getModelPreset: () => ipcRenderer.invoke('workspace:get-model-preset'),
  saveModelPreset: (preset: any) => ipcRenderer.invoke('workspace:save-model-preset', preset),
  createShortcut: () => ipcRenderer.invoke('desktop:create-shortcut'),
  getComputerOverview: () => ipcRenderer.invoke('desktop:computer-overview'),
  listDirectory: (folderPath: any) => ipcRenderer.invoke('desktop:list-directory', folderPath),
  revealPath: (targetPath: string) => ipcRenderer.invoke('desktop:reveal-path', targetPath),
  openPath: (targetPath: string) => ipcRenderer.invoke('desktop:open-path', targetPath),
  openTerminal: (folderPath: any) => ipcRenderer.invoke('desktop:open-terminal', folderPath),
  listPcWindows: () => ipcRenderer.invoke('pc-window:list'),
  focusPcWindow: (id: string) => ipcRenderer.invoke('pc-window:focus', id),
  scanPcUi: (windowId?: string) => ipcRenderer.invoke('pc-ui:scan', { windowId }),
  resolvePcUi: (query: string, role?: string, windowId?: string) => ipcRenderer.invoke('pc-ui:resolve', { query, role, windowId }),
  clickPcUi: (target: string, role?: string, windowId?: string) => ipcRenderer.invoke('pc-ui:click', { target, role, windowId }),
  typePcUi: (target: string, text: string, windowId?: string, role?: string) => ipcRenderer.invoke('pc-ui:type', { target, text, windowId, role }),
  composeWhatsApp: (message: string, phone: any) => ipcRenderer.invoke('desktop:whatsapp-compose', { message, phone }),
  getVoiceStackStatus: () => ipcRenderer.invoke('desktop:voice-stack-status'),
  speakVoiceStack: (text: string, options: any) => ipcRenderer.invoke('desktop:voice-stack-speak', { text, options }),
  diagnoseVoiceStack: () => ipcRenderer.invoke('desktop:voice-stack-diagnose'),
  buildVoiceStack: () => ipcRenderer.invoke('desktop:voice-stack-build'),
  getSilvaEvents: (limit: any) => ipcRenderer.invoke('silva-events:get-recent', limit),
  getAutomationEvents: () => ipcRenderer.invoke('automation:get-events'),
  openBrowserAutomation: (target: any) => ipcRenderer.invoke('automation:open-browser', target),
  researchWebAutomation: (query: string) => ipcRenderer.invoke('automation:research-web', query),
  getBrowserOperatorState: () => ipcRenderer.invoke('browser-operator:get-state'),
  stopBrowserOperator: (reason?: string) => ipcRenderer.invoke('browser-operator:stop-all', reason),
  resumeBrowserOperator: () => ipcRenderer.invoke('browser-operator:resume'),
  openBrowserOperator: (target: any, sessionId: any, label: any) => ipcRenderer.invoke('browser-operator:open', { target, sessionId, label }),
  navigateBrowserOperator: (target: string, sessionId: any) => ipcRenderer.invoke('browser-operator:navigate', { target, sessionId }),
  readBrowserOperator: (sessionId: any) => ipcRenderer.invoke('browser-operator:read', sessionId),
  scanBrowserUi: (sessionId: any) => ipcRenderer.invoke('browser-operator:ui-scan', sessionId),
  resolveBrowserUi: (query: string, role: any, sessionId: any) => ipcRenderer.invoke('browser-operator:ui-resolve', { query, role, sessionId }),
  clickBrowserUi: (target: string, sessionId: any, role: any) => ipcRenderer.invoke('browser-operator:ui-click', { target, sessionId, role }),
  typeBrowserUi: (target: string, text: string, sessionId: any, role: any) => ipcRenderer.invoke('browser-operator:ui-type', { target, text, sessionId, role }),
  clickBrowserOperator: (selector: string, sessionId: any) => ipcRenderer.invoke('browser-operator:click', { selector, sessionId }),
  clickHrefBrowserOperator: (href: string, sessionId: any) => ipcRenderer.invoke('browser-operator:click-href', { href, sessionId }),
  typeBrowserOperator: (selector: string, text: string, sessionId: any) => ipcRenderer.invoke('browser-operator:type', { selector, text, sessionId }),
  pressBrowserOperator: (key: string, sessionId: any) => ipcRenderer.invoke('browser-operator:press', { key, sessionId }),
  scrollBrowserOperator: (amount: number, sessionId: any) => ipcRenderer.invoke('browser-operator:scroll', { amount, sessionId }),
  searchVisibleBrowserOperator: (query: string, sessionId: any, label: any) => ipcRenderer.invoke('browser-operator:search-visible', { query, sessionId, label }),
  screenshotBrowserOperator: (sessionId: any) => ipcRenderer.invoke('browser-operator:screenshot', sessionId),
  inspectBrowserOperator: (sessionId: any) => ipcRenderer.invoke('browser-operator:inspect', sessionId),
  getClassicOutlookStatus: () => ipcRenderer.invoke('outlook:classic-status'),
  listClassicOutlookMessages: (limit: any) => ipcRenderer.invoke('outlook:classic-messages', limit),
  syncClassicOutlookBatch: (arg?: any) => ipcRenderer.invoke('outlook:classic-sync-batch', arg || {}),
  getClassicOutlookSyncState: () => ipcRenderer.invoke('outlook:classic-sync-state'),
  resetClassicOutlookSyncState: () => ipcRenderer.invoke('outlook:classic-reset-sync'),
  startMicrosoftGraphLogin: () => ipcRenderer.invoke('microsoft:graph-start-login'),
  completeMicrosoftGraphLogin: () => ipcRenderer.invoke('microsoft:graph-complete-login'),
  setMicrosoftGraphSecret: (secret: string) => ipcRenderer.invoke('microsoft:graph-set-secret', secret),
  setMicrosoftGraphConfig: (config: any) => ipcRenderer.invoke('microsoft:graph-set-config', config),
  getMicrosoftGraphConfig: () => ipcRenderer.invoke('microsoft:graph-get-config'),
  getMicrosoftGraphStatus: (accountId?: string) => ipcRenderer.invoke('microsoft:graph-status', accountId),
  getMicrosoftMailboxSettings: (accountId?: string) => ipcRenderer.invoke('microsoft:graph-mailbox-settings', accountId),
  listMicrosoftGraphMessages: (arg?: any) => ipcRenderer.invoke('microsoft:graph-messages', typeof arg === 'object' ? arg : { limit: arg }),
  listMicrosoftGraphFolders: (accountId?: string) => ipcRenderer.invoke('microsoft:graph-folders', accountId),
  syncEmailIntelligence: (arg?: any, limitPerFolder?: any) => ipcRenderer.invoke('microsoft:graph-sync-email-intelligence', typeof arg === 'object' ? arg : { accountId: arg, limitPerFolder }),
  syncEmailBatch: (arg?: any, options?: any) => ipcRenderer.invoke('microsoft:graph-sync-email-batch', typeof arg === 'object' && !options ? arg : { accountId: arg, ...(options || {}) }),
  getMailSyncState: (accountId?: string) => ipcRenderer.invoke('microsoft:graph-mail-sync-state', accountId),
  resetMailSyncState: (accountId?: string) => ipcRenderer.invoke('microsoft:graph-reset-mail-sync', accountId),
  runMicrosoftGraphMailAction: (arg: any, action?: any) => ipcRenderer.invoke('microsoft:graph-mail-action', action ? { accountId: arg, action } : arg),
  disconnectMicrosoftGraph: (accountId?: string) => ipcRenderer.invoke('microsoft:graph-disconnect', accountId),
  getMicrosoftGraphAccounts: () => ipcRenderer.invoke('microsoft:graph-list-accounts'),
  searchIndexedEmails: (query: string, accountId?: string) => ipcRenderer.invoke('microsoft:graph-search-index', { query, accountId }),
  getSilvaMemory: () => ipcRenderer.invoke('workspace:get-silva-memory'),
  saveSilvaMemory: (memory: string) => ipcRenderer.invoke('workspace:save-silva-memory', memory),
  getEmailIntelligence: () => ipcRenderer.invoke('workspace:get-email-intelligence'),
  updateMailMemoryItem: (itemId: string, patch: any) => ipcRenderer.invoke('workspace:update-mail-memory-item', { itemId, patch }),
  runTinyFishAgent: (options: any) => ipcRenderer.invoke('tinyfish:run-agent', options),
  setTinyFishApiKey: (key: string) => ipcRenderer.invoke('tinyfish:set-api-key', key),
  getTinyFishApiStatus: () => ipcRenderer.invoke('tinyfish:api-status'),
  getTinyFishStatus: (sessionId: string) => ipcRenderer.invoke('tinyfish:get-status', sessionId),
  approveEmailRoute: (messageId: string, status: string) => ipcRenderer.invoke('workspace:approve-email-route', { messageId, status }),
  getProjects: () => ipcRenderer.invoke('workspace:get-projects'),
  saveProject: (project: any) => ipcRenderer.invoke('workspace:save-project', project),
  deleteProject: (id: string) => ipcRenderer.invoke('workspace:delete-project', id),
  addProjectFiles: (id: string, files: any) => ipcRenderer.invoke('workspace:add-project-files', { id, files }),
  startProjectTask: (id: string, prompt: string, agentId: any) => ipcRenderer.invoke('workspace:start-project-task', { id, prompt, agentId }),
  getWideResearchRuns: () => ipcRenderer.invoke('wide-research:get-runs'),
  getWideResearchBlackboard: (runId: any) => ipcRenderer.invoke('wide-research:get-blackboard', runId),
  startWideResearch: (brief: string, items: any) => ipcRenderer.invoke('wide-research:start', { brief, items }),
  getConnectorStatuses: () => ipcRenderer.invoke('ai:get-connector-statuses'),
  createSlidesArtifact: (title: string, brief: string) => ipcRenderer.invoke('artifacts:create-slides', { title, brief }),
  createWebsiteArtifact: (title: string, brief: string) => ipcRenderer.invoke('artifacts:create-website', { title, brief }),
  createDesignArtifact: (title: string, brief: string) => ipcRenderer.invoke('artifacts:create-design', { title, brief }),
  analyzeDataArtifact: (filePath: string) => ipcRenderer.invoke('artifacts:analyze-data', filePath),
  createJusticeCasePack: (title: string, brief: string) => ipcRenderer.invoke('artifacts:create-justice-case', { title, brief }),
  createPurchaseProtectionPack: (title: string, brief: string) => ipcRenderer.invoke('artifacts:create-purchase-protection', { title, brief }),
  revealArtifactsRoot: () => ipcRenderer.invoke('artifacts:reveal-root'),
});
