/// <reference types="vite/client" />

interface Window {
  // expose in the `electron/preload.ts`
  ipcRenderer: import('electron').IpcRenderer & {
    listModels: () => Promise<any[]>;
    chat: (data: { model: string, messages: any[], provider?: string }) => Promise<any>;
    checkLMStudio: () => Promise<any>;
    checkOpenCode: () => Promise<any>;
    listOpenCodeModels: () => Promise<any[]>;
    checkJan: () => Promise<any>;
    janStatus: () => Promise<{ apiOnline: boolean, installed: boolean, executablePath: string, activeModel: string, models: any[] }>;
    modelHubDiagnostics?: () => Promise<any>;
    startJan: () => Promise<{ ok: boolean, message?: string, error?: string, alreadyOnline?: boolean, status?: any }>;
    loadJanModel: (model: { name: string, path?: string }) => Promise<{ ok: boolean, model?: string, warning?: string, error?: string, status?: any }>;
    scanPC: () => Promise<{ gpu: string, vram: string, ram: string, os: string, approximate?: boolean }>;
    searchHF: (query: string) => Promise<any[]>;
    downloadHF: (modelId: string) => Promise<{ ok: boolean, path?: string, error?: string }>;
    getModelsPath: () => Promise<string>;
    listLibraryModels: () => Promise<any[]>;
    deleteLibraryModel: (modelId: string) => Promise<boolean>;
    revealModelsFolder: () => Promise<boolean>;
    chatProvider: (data: any) => Promise<any>;
    getConnectors: () => Promise<{[key: string]: boolean}>;
    connectGoogle: () => Promise<{ success: boolean, email?: string }>;
    saveAPIKey: (provider: string, key: string) => Promise<boolean>;
    getAPIKeys: () => Promise<{[key: string]: string}>;
    getKnowledge: () => Promise<any[]>;
    saveKnowledge: (knowledge: any) => Promise<boolean>;
    openApp: (appName: string) => Promise<boolean>;
    selectFiles: () => Promise<string[]>;
    selectFolder: () => Promise<string>;
    analyzeUK: (path: string, type: 'legal' | 'tax') => Promise<any>;
    createShortcut: () => Promise<{ success: boolean, path?: string, error?: string }>;
    getComputerOverview: () => Promise<any>;
    listDirectory: (folderPath?: string) => Promise<{ path: string, entries: any[] }>;
    revealPath: (targetPath: string) => Promise<{ ok: boolean, path?: string, error?: string }>;
    openPath: (targetPath: string) => Promise<{ ok: boolean, path?: string, error?: string }>;
    openTerminal: (folderPath?: string) => Promise<{ ok: boolean, path?: string }>;
    composeWhatsApp: (message: string, phone?: string) => Promise<{ ok: boolean, url: string, mode: string }>;
    getVoiceStackStatus: () => Promise<{ ok: boolean, url: string, status?: number, error?: string, profiles?: any, accents?: any }>;
    speakVoiceStack: (text: string, options?: any) => Promise<{ ok: boolean, mode?: string, endpoint?: string, voice?: string, language?: string, path?: string, error?: string }>;
    diagnoseVoiceStack: () => Promise<any>;
    buildVoiceStack: () => Promise<{ ok: boolean, mode?: string, script?: string, message?: string, error?: string }>;
    getSilvaEvents: (limit?: number) => Promise<any[]>;
    getAutomationEvents: () => Promise<any[]>;
    openBrowserAutomation: (target?: string) => Promise<{ ok: boolean, url?: string, error?: string, event?: any }>;
    researchWebAutomation: (query: string) => Promise<{ ok: boolean, url?: string, error?: string, event?: any, query?: string }>;
    getBrowserOperatorState: () => Promise<any>;
    openBrowserOperator: (target?: string, sessionId?: string, label?: string) => Promise<any>;
    navigateBrowserOperator: (target: string, sessionId?: string) => Promise<any>;
    readBrowserOperator: (sessionId?: string) => Promise<any>;
    clickBrowserOperator: (selector: string, sessionId?: string) => Promise<any>;
    typeBrowserOperator: (selector: string, text: string, sessionId?: string) => Promise<any>;
    screenshotBrowserOperator: (sessionId?: string) => Promise<any>;
    inspectBrowserOperator: (sessionId?: string) => Promise<any>;
    getClassicOutlookStatus: () => Promise<any>;
    listClassicOutlookMessages: (limit?: number) => Promise<any[] | { ok: false, error: string }>;
    syncClassicOutlookBatch?: (arg?: any) => Promise<any>;
    getClassicOutlookSyncState?: () => Promise<any>;
    resetClassicOutlookSyncState?: () => Promise<any>;
    startMicrosoftGraphLogin: () => Promise<any>;
    completeMicrosoftGraphLogin: () => Promise<any>;
    setMicrosoftGraphSecret?: (secret: string) => Promise<any>;
    getMicrosoftGraphStatus: (accountId?: string) => Promise<any>;
    getMicrosoftMailboxSettings: (accountId?: string) => Promise<any>;
    listMicrosoftGraphMessages: (arg?: any) => Promise<any[]>;
    listMicrosoftGraphFolders: (accountId?: string) => Promise<any[]>;
    syncEmailIntelligence: (arg?: any, limitPerFolder?: number) => Promise<any>;
    syncEmailBatch: (arg?: any, options?: any) => Promise<any>;
    getMailSyncState: (accountId?: string) => Promise<any>;
    resetMailSyncState: (accountId?: string) => Promise<any>;
    runMicrosoftGraphMailAction: (arg: any, action?: any) => Promise<any>;
    disconnectMicrosoftGraph: (accountId?: string) => Promise<{ ok: boolean }>;
    getSilvaMemory: () => Promise<string>;
    saveSilvaMemory: (memory: string) => Promise<boolean>;
    getEmailIntelligence: () => Promise<any>;
    approveEmailRoute: (messageId: string, status: string) => Promise<any>;
    getWhatsAppDrafts: () => Promise<any[]>;
    saveWhatsAppDraft: (draft: any) => Promise<any>;
    markWhatsAppOpened: (id: string) => Promise<any>;
    getWhatsAppChannelStatus: () => Promise<any>;
    ensureWhatsAppActive: () => Promise<any>;
    getWhatsAppChannelSettings: () => Promise<any>;
    saveWhatsAppChannelSettings: (settings: any) => Promise<any>;
    getWhatsAppRoutes: () => Promise<any[]>;
    routeWhatsAppMessage: (text: string, from?: string) => Promise<any>;
    composeWhatsAppDraft: (draftId: string) => Promise<any>;
    getScheduledTasks: () => Promise<any[]>;
    saveScheduledTasks: (tasks: any[]) => Promise<boolean>;
    runScheduledTask: (id: string) => Promise<any>;
    getScheduledRuns: () => Promise<any[]>;
    getModelPreset: () => Promise<{ provider: string, model: string }>;
    saveModelPreset: (preset: { provider: string, model: string }) => Promise<{ provider: string, model: string }>;
    getProjects: () => Promise<any[]>;
    saveProject: (project: any) => Promise<any>;
    deleteProject: (id: string) => Promise<any[]>;
    addProjectFiles: (id: string, files: string[]) => Promise<any>;
    startProjectTask: (id: string, prompt: string, agentId?: string) => Promise<any>;
    getWideResearchRuns: () => Promise<any[]>;
    getWideResearchBlackboard: (runId?: string) => Promise<any[]>;
    startWideResearch: (brief: string, items?: string[]) => Promise<any>;
    getConnectorStatuses: () => Promise<Record<string, any>>;
    createSlidesArtifact: (title: string, brief: string) => Promise<any>;
    createWebsiteArtifact: (title: string, brief: string) => Promise<any>;
    createDesignArtifact: (title: string, brief: string) => Promise<any>;
    analyzeDataArtifact: (filePath: string) => Promise<any>;
    createJusticeCasePack: (title: string, brief: string) => Promise<any>;
    createPurchaseProtectionPack: (title: string, brief: string) => Promise<any>;
    revealArtifactsRoot: () => Promise<any>;

    // Tool Registry
    getTools: () => Promise<any[]>;
    saveConnector: (connector: any) => Promise<{[key: string]: boolean}>;
    toggleConnector: (id: string, enabled: boolean) => Promise<{[key: string]: boolean}>;
    executeTool: (toolId: string, params: any) => Promise<any>;

    // Skills Engine
    getInstalledSkills: () => Promise<string[]>;
    getSkillPackages: () => Promise<any[]>;
    getSkillGuidance: () => Promise<{ installed: string[], prompt: string }>;
    toggleSkill: (skillId: string, installed: boolean) => Promise<string[]>;
    proposeSkill: (action: any) => Promise<any>;
    getPendingSkills: () => Promise<any[]>;
    approveSkill: (id: string) => Promise<any>;
    denySkill: (id: string) => Promise<boolean>;

    // Multi-Agent Orchestrator
    getAgents: () => Promise<any[]>;
    updateAgentStatus: (id: string, status: string, background: boolean) => Promise<boolean>;
    createAgentTask: (input: string, agentId?: string) => Promise<any>;
    getAgentTasks: () => Promise<any[]>;
    invoke: (channel: string, ...args: any[]) => Promise<any>;
    removeAllListeners: (channel: string) => void;
    getResourceUsage: () => Promise<{ cpu: number, ram: number, gpu: number, gpuModel: string, engine?: string }>;
    engineStatus: () => Promise<any>;
    chatBest: (data: { model: string, messages: any[] }) => Promise<any>;
  }
}
